
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTMwNjkxMzB9.Jj6vTdYJ1wUAGY6BlbdyCQuNUvxjdr7RIqsg22GP6eI

###


POST http://localhost:3000/carted_products
Content-type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 5,
  "quantity": 3,
  "status": "carted",
  "order_id": ""
}

###

Get http://localhost:3000/carted_products
Content-type: application/json
Authorization: Bearer {{jwt}}
