
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTMwNjkxMzB9.Jj6vTdYJ1wUAGY6BlbdyCQuNUvxjdr7RIqsg22GP6eI

###


POST http://localhost:3000/carted_products
Content-type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 3,
  "product_id": 6,
  "quantity": 2,
  "status": "carted",
  "order_id": ""
}

