
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sam Bates",
  "email": "Sam@test.com",
  "password": "password1",
  "password_confirmation": "password1"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Sam@test.com",
  "password": "password1"
}


### Photos create
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4OTE1NDl9.p8XtI4RV8CZRgQmTdFCPvY0gWLnIeTkc-lF0KMxP-1E
Content-Type: application/json

{
  "name": "Scented Candle 1",
  "price": "4.99",
  "description": "Cinnamon-scented candle",
  "inventory": 35,
  "supplier_id": 1
}

### Creates Order

Post http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4OTE1NDl9.p8XtI4RV8CZRgQmTdFCPvY0gWLnIeTkc-lF0KMxP-1E
Content-Type: application/json

{ 
    "product_id": 2,
    "quantity": 5
}

### See all orders for current user

Get http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4MjEwMTR9.fRo9pTfRS15QU3o70spwGrwZFfJoWKimWzwXlk2DpSs
Content-Type: application/json

### See single order

Get http://localhost:3000/orders/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTI4MjEwMTR9.fRo9pTfRS15QU3o70spwGrwZFfJoWKimWzwXlk2DpSs
Content-Type: application/json